#!/usr/bin/env python3
"""tools/se_provision.py - step 6b (PC side): build the provisioning header
that firmware/se_provision uses to load the LoRa link keys into slot 10.

    python3 tools/se_provision.py keys/secure_link_keys.h docs/step5_identity_key_output.txt

Inputs
  keys/secure_link_keys.h            SL_ENC_KEY / SL_MIC_KEY (gen_keys.py format, SECRET)
  docs/step5_identity_key_output.txt the identity public key exported in step 5
Output
  firmware/se_provision/se_provision_data.h   (SECRET - git-ignored)
    SE_LINK_KEYS[32]      enc key (AES key block 0) then MIC key (key block 1)
    SE_KAT_PT/SE_KAT_CT   known-answer blocks computed here on the PC with the
                          same keys: after the data lock the chip must
                          reproduce them from slot 10, which proves the keys
                          went in correctly without ever reading them back
    SE_IDENTITY_PUBKEY    slot 0 must still hold this key before locking
Needs: pip install cryptography
"""
import argparse
import os
import re
import sys

from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import se_pubkey  # noqa: E402

# Fixed, non-secret test blocks (any value works; these are easy to recognise).
KAT_PT = [bytes(range(0x00, 0x10)), bytes(range(0xF0, 0x100))]


def parse_keys(text):
    keys = {}
    for name in ("SL_ENC_KEY", "SL_MIC_KEY"):
        m = re.search(name + r"\s*\[\s*16\s*\]\s*=\s*\{([^}]*)\}", text)
        if not m:
            raise ValueError("%s[16] not found" % name)
        vals = [int(v, 0) for v in re.findall(r"0x[0-9A-Fa-f]{1,2}|\b\d+\b", m.group(1))]
        if len(vals) != 16 or any(v > 0xFF for v in vals):
            raise ValueError("%s must have 16 byte values, found %d" % (name, len(vals)))
        k = bytes(vals)
        if k == bytes(16):
            raise ValueError("%s is all zero - that is the example file, not real keys" % name)
        keys[name] = k
    if keys["SL_ENC_KEY"] == keys["SL_MIC_KEY"]:
        raise ValueError("encryption and MIC keys must differ")
    return keys["SL_ENC_KEY"], keys["SL_MIC_KEY"]


def aes_ecb(key, block):
    e = Cipher(algorithms.AES(key), modes.ECB()).encryptor()
    return e.update(block) + e.finalize()


def c_bytes(b, indent="  "):
    rows = [indent + ", ".join("0x%02X" % x for x in b[i:i + 16]) for i in range(0, len(b), 16)]
    return ",\n".join(rows)


def build_header(enc, mic, pubkey):
    ct = [aes_ecb(enc, KAT_PT[0]), aes_ecb(mic, KAT_PT[1])]
    out = ["/* GENERATED by tools/se_provision.py - SECRET (contains the link keys). DO NOT COMMIT. */",
           "#pragma once", "#include <stdint.h>", "",
           "/* Slot 10, block 0: AES key block 0 = encryption key, key block 1 = MIC key */",
           "static const uint8_t SE_LINK_KEYS[32] = {", c_bytes(enc + mic), "};", "",
           "/* Known answers computed on the PC: AES-128(key block i, SE_KAT_PT[i]) */",
           "static const uint8_t SE_KAT_PT[2][16] = {",
           "  {" + c_bytes(KAT_PT[0], " ") + " },", "  {" + c_bytes(KAT_PT[1], " ") + " } };",
           "static const uint8_t SE_KAT_CT[2][16] = {",
           "  {" + c_bytes(ct[0], " ") + " },", "  {" + c_bytes(ct[1], " ") + " } };", "",
           "/* Identity public key recorded in step 5 (X||Y) - slot 0 must still match */",
           "static const uint8_t SE_IDENTITY_PUBKEY[64] = {", c_bytes(pubkey), "};", ""]
    return "\n".join(out), ct


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("keys_header")
    ap.add_argument("step5_output")
    ap.add_argument("--out", default=os.path.join(HERE, "..", "firmware", "se_provision", "se_provision_data.h"))
    a = ap.parse_args(argv)
    with open(a.keys_header) as f:
        enc, mic = parse_keys(f.read())
    with open(a.step5_output) as f:
        pub = se_pubkey.parse_pubkey(f.read())
    se_pubkey.to_public_key(pub)                       # must be a valid P-256 point
    text, ct = build_header(enc, mic, pub)
    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    with open(a.out, "w") as f:
        f.write(text)
    print("Wrote %s (SECRET - git-ignored)" % os.path.normpath(a.out))
    print("Known answers the chip must reproduce after the lock:")
    print("  key block 0 (enc): %s" % ct[0].hex().upper())
    print("  key block 1 (MIC): %s" % ct[1].hex().upper())
    print("Identity key fingerprint: %s" % se_pubkey.fingerprint(pub))
    return 0


if __name__ == "__main__":
    sys.exit(main())
